apiVersion: v1
kind: ConfigMap
metadata:
  name: map-mysql-initdb-config
data:
  initdb.sql: |
    CREATE DATABASE IF NOT EXISTS micro_mapping;
    CREATE TABLE IF NOT EXISTS `micro_mapping`.`orders` (
      `id` VARCHAR(255) NOT NULL,
      `drone_name` VARCHAR(255) NOT NULL,
      `location_id` SMALLINT NOT NULL,
      `location_geo` VARCHAR(255) NOT NULL,
      `status` SMALLINT NOT NULL,
      PRIMARY KEY (`id`)
    );

---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: map-mysql
  labels:
    app: map-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: map-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: map-mysql
    spec:
      containers:
      - image: mysql:5.7
        args:
          - "--ignore-db-dir=lost+found"
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: map-mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: map-mysql-pv-claim
      - name: map-mysql-initdb
        configMap:
          name: map-mysql-initdb-config
---
    
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: map-mysql-pv-claim
  labels:
    app: map-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi    

---
    
apiVersion: v1
kind: Service
metadata:
  name: map-mysql-service
  labels:
    app: map-mysql-service
spec:
  ports:
    - port: 3306
  selector:
    app: map-mysql
  clusterIP: None    