apiVersion: v1
kind: ConfigMap
metadata:
  name: order-conf
  labels:
    name: order-conf
data:
  env: |
    APP_ENV=prod
    APP_PORT=3003
    MICRO_DRONES_URL=http://drones-service:8081
    MICRO_MAPPING_URL=http://localhost:3000
    RABBITMQ_HOST=rabbitmq-service
    RABBITMQ_USER=rabbitmq
    MYSQL_HOST=order-mysql-service
    MYSQL_USER=root
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  selector:
    matchLabels:
      app: order

  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: wy7images/dd-orders
          ports:
            - containerPort: 3003
          env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: rabbitmq-pass
          envFrom:
            - configMapRef:
                name: order-conf
          volumeMounts:
          - name: order-conf
            subPath: .env
            mountPath: /home/node/app/.env

      volumes:
      - name: order-conf
        configMap:
          name: order-conf
          items:
            - key: env
              path: .env
          

---

apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3003
  selector:
    app: order
